%YAML 1.1
---
version: "1.0.0"
user: <tesla user name>
passwd: <tesla password>
dbDir: ./teslas
schema: ./dbSchema.yml
logLevel: WARNING
logFile: /tmp/teslaWatch.log
cars:
  <vin>:
    notifiers:
      <notifier>:
        - <eventType>
        - <eventType>
    regions:
      - HOME:
        xxx
      - WORK:
        yyy
      - <region1>:
        aaa
      - <region2>:
        bbb
      - <region3>:
        ccc
    settings:
      intervals:
        '<????>': 0
      thresholds:
        'distance': 0
    VIN: <vin>
  <vin>:
    VIN: <vin>
