%YAML 1.1
---
VERSION: "1.0.0"
USER: <tesla user name>
PASSWD: <tesla password>
DB: ./teslas.db
CARS:
  <vin>:
    VIN: <vin>
    nickname: <string>
    regions:
      - HOME:
        xxx
      - WORK:
        yyy
      - <region1>:
        aaa
      - <region2>:
        bbb
      - <region3>:
        ccc
  <vin>:
    VIN: <vin>
    nickname: <string>
