%YAML 1.1
---
version: "1.0.0"
user: <tesla user name>
passwd: <tesla password>
dbDir: ./teslas
schema: ./dbSchema.yml
logLevel: WARNING
logFile: /tmp/teslaWatch.log
cars:
  <vin>:
    VIN: <vin>
    notifiers:
      SMS:
        REGION_ENTER:
          - HOME
          - WORK
        REGION_EXIT
          - HOME
          - WORK
      email:
        ????:
          - ABOVE
          - BELOW
      myFunction2:
        ????:
          - ????
    nickname: <string>
    regions:
      - HOME:
        xxx
      - WORK:
        yyy
      - <region1>:
        aaa
      - <region2>:
        bbb
      - <region3>:
        ccc
  <vin>:
    VIN: <vin>
    nickname: <string>
settings:
  intervals:
    '<????>': 0
  thresholds:
    'distance': 0
eventNotifiers:
  '<eventType>': <notifier>
